### ISSUE TITLE
1.16.3 Support

### ISSUE THREAD

**Issue by mibby** [xuancat0208/XuanCatAPI#1]
Please add support for ~~1.16.2~~ 1.16.3.

```
[09:14:51] [Server thread/INFO]: [XuanCatAPI] Enabling XuanCatAPI v14~16-1.0.2
[09:14:51] [Server thread/ERROR]: Error occurred while enabling XuanCatAPI v14~16-1.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R1/Packet
	at xuan.cat.xuancatapi.code.Index.onEnable(Index.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:242) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 11 more
[09:14:51] [Server thread/INFO]: [XuanCatAPI] Disabling XuanCatAPI v14~16-1.0.2
[09:14:51] [Server thread/INFO]: [ViewDistanceCat] Enabling ViewDistanceCat v4.4.4
[09:14:51] [Server thread/ERROR]: Error occurred while enabling ViewDistanceCat v4.4.4 (Is it up to date?)
java.lang.NoClassDefFoundError: xuan/cat/xuancatapi/api/event/packet/PacketEvent
	at xuan.cat.viewdistancecat.code.Index.onEnable(Index.java:32) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:242) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassNotFoundException: xuan.cat.xuancatapi.api.event.packet.PacketEvent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:435) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Tuinity-"f3928b6"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 11 more
[09:14:51] [Server thread/INFO]: [ViewDistanceCat] Disabling ViewDistanceCat v4.4.4
```

**Comment by xuancat0208** [comment]
finished
